name: macOS WebShell
on: workflow_dispatch

jobs:
  debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        id: tmate
      - name: Show connection info
        run: |
          echo "----------------------------------"
          echo "ðŸ”— Web Shell URL:"
          echo "${{ steps.tmate.outputs.web-url }}"
          echo
          echo "ðŸ’» SSH Command:"
          echo "${{ steps.tmate.outputs.ssh }}"
          echo "----------------------------------"
